### PR TITLE
#259 Catch correctly a failure to connect to collections API

### LINKED ISSUE #259: Error handling GraphQL: Better error message for API not available
`Error creating collection: GraphQL error: Cannot read property 'response' of undefined` shows in the UI, but this is due to the collections-api not being present. Internal server error should be returned in that case

### PR DESCRIPTION
**Pull request by dfernandezm**
Fixes #259 
- [x] Detect a connection failure when GraphQL cannot connect to collections API
- [x] E2E Graphql test showcase
- [x] Self review

### CODE REVIEW

File: server/packages/graphql/src/resolverMap.ts [hunk 1]
```diff
@@ -74,10 +75,14 @@ const resolverMap: IResolvers = {
...
-            let { collection } = args
-            console.log(`About to create collection for ${collection.collectorId}: ${collection.name}, ${collection.description}`);
-            let { collectionId, name, description, collectorId } = await dataSources.collectionsAPI.createCollection(collection);
-            return new BankNoteCollection(collectionId, name, description, collectorId, []);
+            try {
+                let { collection } = args
+                console.log(`About to create collection for ${collection.collectorId}: ${collection.name}, ${collection.description}`);
+                let { collectionId, name, description, collectorId } = await dataSources.collectionsAPI.createCollection(collection);
+                return new BankNoteCollection(collectionId, name, description, collectorId, []);     
+            } catch (err) {
```
Comment (dfernandezm) [inline server/packages/graphql/src/resolverMap.ts:83]: need to add the try/catch to all collection resolvers (separate issue?)

File: server/packages/graphql/src/resolverMap.ts [hunk 2]
```diff
@@ -251,8 +256,9 @@ const decorateBanknoteCollection =
         return new BankNoteCollection(collection.id, collection.name, collection.description, collection.collectorId, bankNotes);
     }
 
-    //TODO: these errors contain lots of information in stacktrace, should be cut to minimum information
-const handleErrors = (err: Error, request: string): Error => {
+//TODO: these errors contain lots of information in stacktrace, should be cut to minimum information
+// https://www.apollographql.com/docs/apollo-server/data/errors/#custom-errors
```
Comment (dfernandezm) [inline server/packages/graphql/src/resolverMap.ts]: Create issue for this TODO

File: server/packages/graphql/src/schema.ts [hunk 3]
```diff
@@ -1,5 +1,6 @@
 import 'graphql-import-node';
-import * as typeDefs from './schema/schema.graphql';
+//import * as typeDefs from './schema/schema.graphql';
```
Comment (dfernandezm) [inline server/packages/graphql/src/schema.ts]: remove

File: server/packages/graphql/test/gql.test.ts [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+            description: "This is my collection",
+        }
+
+        const { mutate } = createTestClient(server);
+        const result = await mutate({
+            mutation: CREATE_COLLECTION,
+            variables: { collection: collectionInput },
+        });
+
+        console.log("Result", result.errors[0].extensions.code);
```
Comment (dfernandezm) [inline server/packages/graphql/test/gql.test.ts]: remove

File: server/packages/graphql/test/gql.test.ts [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+        const errorMessage = result.errors[0].message
+        const errorCode = result.errors[0].extensions.code
+      
+        expect(errorCode).toBe('CONNECTION_REFUSED');
```
Comment (dfernandezm) [inline server/packages/graphql/test/gql.test.ts]: constant shared?

File: server/packages/graphql/src/resolverMap.ts [hunk 6]
```diff
@@ -263,7 +269,13 @@ const handleErrors = (err: Error, request: string): Error => {
         console.log(`Forbidden access during operation ${request}`);
         return err;    
     } else {
-        return new Error(`General error in ${request}: ${err.message}`);
+        let newErr = new GeneralError(`General error in ${request}: ${err.message}`, err["code"]);
+        console.log("Err", err["code"])
+        if (err["code"] === "ECONNREFUSED") {
```
Comment (dfernandezm) [inline server/packages/graphql/src/resolverMap.ts:275]: constant
